backend:
  name: github
  repo: maxojj/fuwari
  branch: main
  base_url: https://decap-cms-oss-oauth.vercel.app

media_folder: "src/assets/images"
public_folder: "src/assets/images"

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "src/content/posts"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{english_slug}}"
    
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "URL 英文名", name: "english_slug", widget: "string", hint: "仅限小写字母、数字和横线，用于生成文件名" }
      - { 
          label: "发布日期", 
          name: "published", 
          widget: "datetime", 
          format: "YYYY-MM-DD HH:mm:ss",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm:ss",
          picker_utc: false 
        }
      - { label: "描述", name: "description", widget: "string", required: false }
      - { label: "封面图片", name: "image", widget: "image", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false, hint: "输入后按回车添加多个" }
      - { label: "分类", name: "category", widget: "string", required: false }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
      - { label: "正文内容", name: "body", widget: "markdown" }
