name: Sync Movie

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create data folder
        run: mkdir -p public/data

      - name: Download movies
        run: |
          curl \
            -H "accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.NEODB_ACCESS_TOKEN }}" \
            "https://neodb.social/api/me/shelf/complete?category=movie&page=1" \
            > public/data/movie.json

      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update movie data
